<?php

namespace Container8CdoO0X;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getExpireOrdersCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\ExpireOrdersCommand' shared autowired service.
     *
     * @return \App\Command\ExpireOrdersCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'Command.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'ExpireOrdersCommand.php';

        $container->privates['App\\Command\\ExpireOrdersCommand'] = $instance = new \App\Command\ExpireOrdersCommand(($container->privates['App\\Repository\\OrderRequestRepository'] ?? $container->load('getOrderRequestRepositoryService')), ($container->privates['App\\Service\\OrderLifecycleService'] ?? $container->load('getOrderLifecycleServiceService')));

        $instance->setName('app:orders:expire');
        $instance->setDescription('Marks overdue pickup orders as expired and releases reserved copies');

        return $instance;
    }
}
