--
-- PostgreSQL database dump
--

\restrict KRk9mMtl7CqE4DbKcqoEWRarLYpKaMxndigQjQ46HzXsFmvcR80srafX9XnI1RO

-- Dumped from database version 15.15
-- Dumped by pg_dump version 15.15

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: acquisition_budget; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.acquisition_budget (
    id integer NOT NULL,
    name character varying(160) NOT NULL,
    fiscal_year character varying(9) NOT NULL,
    allocated_amount numeric(12,2) NOT NULL,
    spent_amount numeric(12,2) NOT NULL,
    currency character varying(3) NOT NULL,
    created_at timestamp(0) without time zone NOT NULL,
    updated_at timestamp(0) without time zone NOT NULL
);


--
-- Name: acquisition_budget_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.acquisition_budget_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: acquisition_budget_id_seq1; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.acquisition_budget ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.acquisition_budget_id_seq1
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: acquisition_expense; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.acquisition_expense (
    id integer NOT NULL,
    budget_id integer NOT NULL,
    order_id integer,
    amount numeric(12,2) NOT NULL,
    currency character varying(3) NOT NULL,
    description character varying(255) NOT NULL,
    type character varying(20) NOT NULL,
    posted_at timestamp(0) without time zone NOT NULL
);


--
-- Name: acquisition_expense_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.acquisition_expense_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: acquisition_expense_id_seq1; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.acquisition_expense ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.acquisition_expense_id_seq1
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: acquisition_order; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.acquisition_order (
    id integer NOT NULL,
    supplier_id integer NOT NULL,
    budget_id integer,
    reference_number character varying(120) DEFAULT NULL::character varying,
    title character varying(255) NOT NULL,
    description text,
    items json,
    total_amount numeric(12,2) NOT NULL,
    currency character varying(3) NOT NULL,
    status character varying(20) NOT NULL,
    created_at timestamp(0) without time zone NOT NULL,
    updated_at timestamp(0) without time zone NOT NULL,
    ordered_at timestamp(0) without time zone DEFAULT NULL::timestamp without time zone,
    expected_at timestamp(0) without time zone DEFAULT NULL::timestamp without time zone,
    received_at timestamp(0) without time zone DEFAULT NULL::timestamp without time zone,
    cancelled_at timestamp(0) without time zone DEFAULT NULL::timestamp without time zone
);


--
-- Name: acquisition_order_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.acquisition_order_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: acquisition_order_id_seq1; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.acquisition_order ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.acquisition_order_id_seq1
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: announcement; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.announcement (
    id integer NOT NULL,
    created_by_id integer NOT NULL,
    title character varying(255) NOT NULL,
    content text NOT NULL,
    type character varying(20) NOT NULL,
    status character varying(20) NOT NULL,
    is_pinned boolean NOT NULL,
    show_on_homepage boolean NOT NULL,
    created_at timestamp(0) without time zone NOT NULL,
    updated_at timestamp(0) without time zone NOT NULL,
    published_at timestamp(0) without time zone DEFAULT NULL::timestamp without time zone,
    expires_at timestamp(0) without time zone DEFAULT NULL::timestamp without time zone,
    target_audience json
);


--
-- Name: announcement_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.announcement_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: announcement_id_seq1; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.announcement ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.announcement_id_seq1
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: app_user; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.app_user (
    id integer NOT NULL,
    email character varying(180) NOT NULL,
    name character varying(255) NOT NULL,
    roles json NOT NULL,
    password character varying(255) NOT NULL,
    phone_number character varying(30) DEFAULT NULL::character varying,
    address_line character varying(255) DEFAULT NULL::character varying,
    city character varying(120) DEFAULT NULL::character varying,
    postal_code character varying(12) DEFAULT NULL::character varying,
    blocked boolean DEFAULT false NOT NULL,
    verified boolean DEFAULT false NOT NULL,
    verified_at timestamp(0) without time zone DEFAULT NULL::timestamp without time zone,
    pending_approval boolean DEFAULT false NOT NULL,
    membership_group character varying(64) DEFAULT 'standard'::character varying NOT NULL,
    loan_limit integer DEFAULT 5 NOT NULL,
    blocked_reason character varying(255) DEFAULT NULL::character varying,
    created_at timestamp(0) without time zone NOT NULL,
    updated_at timestamp(0) without time zone NOT NULL,
    privacy_consent_at timestamp(0) without time zone DEFAULT NULL::timestamp without time zone,
    newsletter_subscribed boolean DEFAULT true NOT NULL,
    pesel character varying(11),
    card_number character varying(20),
    card_expiry timestamp without time zone,
    account_status character varying(50),
    keep_history boolean DEFAULT false NOT NULL,
    email_loans boolean DEFAULT true NOT NULL,
    email_reservations boolean DEFAULT true NOT NULL,
    email_fines boolean DEFAULT true NOT NULL,
    email_announcements boolean DEFAULT false NOT NULL,
    preferred_contact character varying(20),
    default_branch character varying(50),
    theme character varying(20),
    font_size character varying(20),
    language character varying(5),
    pin character varying(4),
    preferred_categories json,
    taste_embedding vector(1536),
    onboarding_completed boolean DEFAULT false
);


--
-- Name: app_user_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.app_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: app_user_id_seq1; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.app_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.app_user_id_seq1
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: audit_logs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.audit_logs (
    id integer NOT NULL,
    user_id integer,
    entity_type character varying(50) NOT NULL,
    entity_id integer,
    action character varying(20) NOT NULL,
    ip_address character varying(45) DEFAULT NULL::character varying,
    old_values text,
    new_values text,
    description text,
    created_at timestamp(0) without time zone NOT NULL
);


--
-- Name: audit_logs_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.audit_logs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: audit_logs_id_seq1; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.audit_logs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.audit_logs_id_seq1
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: author; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.author (
    id integer NOT NULL,
    name character varying(255) NOT NULL
);


--
-- Name: author_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.author_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: author_id_seq1; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.author ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.author_id_seq1
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: backup_record; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.backup_record (
    id integer NOT NULL,
    file_name character varying(190) NOT NULL,
    file_path character varying(255) NOT NULL,
    file_size integer NOT NULL,
    status character varying(32) NOT NULL,
    created_at timestamp(0) without time zone NOT NULL,
    initiated_by character varying(120) DEFAULT NULL::character varying
);


--
-- Name: backup_record_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.backup_record_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: backup_record_id_seq1; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.backup_record ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.backup_record_id_seq1
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: book; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.book (
    id integer NOT NULL,
    author_id integer NOT NULL,
    title character varying(255) NOT NULL,
    isbn character varying(20) DEFAULT NULL::character varying,
    copies integer NOT NULL,
    total_copies integer NOT NULL,
    storage_copies integer NOT NULL,
    open_stack_copies integer NOT NULL,
    description text,
    embedding vector(1536),
    search_vector tsvector,
    publisher character varying(180) DEFAULT NULL::character varying,
    publication_year smallint,
    resource_type character varying(60) DEFAULT NULL::character varying,
    signature character varying(60) DEFAULT NULL::character varying,
    target_age_group character varying(24) DEFAULT NULL::character varying,
    created_at timestamp(0) without time zone NOT NULL
);


--
-- Name: book_category; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.book_category (
    book_id integer NOT NULL,
    category_id integer NOT NULL
);


--
-- Name: book_collection; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.book_collection (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    description text,
    featured boolean NOT NULL,
    display_order integer NOT NULL,
    created_at timestamp(0) without time zone NOT NULL,
    updated_at timestamp(0) without time zone DEFAULT NULL::timestamp without time zone,
    curated_by_id integer NOT NULL
);


--
-- Name: book_collection_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.book_collection ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.book_collection_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: book_copy; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.book_copy (
    id integer NOT NULL,
    book_id integer NOT NULL,
    inventory_code character varying(60) NOT NULL,
    status character varying(20) NOT NULL,
    location character varying(120) DEFAULT NULL::character varying,
    access_type character varying(30) NOT NULL,
    condition_state character varying(120) DEFAULT NULL::character varying,
    created_at timestamp(0) without time zone NOT NULL,
    updated_at timestamp(0) without time zone NOT NULL
);


--
-- Name: book_copy_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.book_copy_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: book_copy_id_seq1; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.book_copy ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.book_copy_id_seq1
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: book_digital_asset; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.book_digital_asset (
    id integer NOT NULL,
    book_id integer NOT NULL,
    label character varying(255) NOT NULL,
    original_filename character varying(255) NOT NULL,
    mime_type character varying(100) NOT NULL,
    size integer NOT NULL,
    storage_name character varying(255) NOT NULL,
    created_at timestamp(0) without time zone NOT NULL
);


--
-- Name: book_digital_asset_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.book_digital_asset_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: book_digital_asset_id_seq1; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.book_digital_asset ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.book_digital_asset_id_seq1
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: book_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.book_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: book_id_seq1; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.book ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.book_id_seq1
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: category; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.category (
    id integer NOT NULL,
    name character varying(120) NOT NULL
);


--
-- Name: category_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.category_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: category_id_seq1; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.category ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.category_id_seq1
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: collection_books; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.collection_books (
    book_collection_id integer NOT NULL,
    book_id integer NOT NULL
);


--
-- Name: doctrine_migration_versions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.doctrine_migration_versions (
    version character varying(191) NOT NULL,
    executed_at timestamp(0) without time zone DEFAULT NULL::timestamp without time zone,
    execution_time integer
);


--
-- Name: favorite; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.favorite (
    id integer NOT NULL,
    user_id integer NOT NULL,
    book_id integer NOT NULL,
    created_at timestamp(0) without time zone NOT NULL
);


--
-- Name: favorite_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.favorite_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: favorite_id_seq1; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.favorite ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.favorite_id_seq1
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: user_book_interaction; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_book_interaction (
    id integer NOT NULL,
    user_id integer NOT NULL,
    book_id integer NOT NULL,
    type character varying(20) NOT NULL,
    rating smallint,
    created_at timestamp(0) without time zone NOT NULL
);


--
-- Name: user_book_interaction_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.user_book_interaction_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: user_book_interaction_id_seq1; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.user_book_interaction ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_book_interaction_id_seq1
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: fine; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.fine (
    id integer NOT NULL,
    loan_id integer NOT NULL,
    amount numeric(8,2) NOT NULL,
    currency character varying(3) NOT NULL,
    reason character varying(255) NOT NULL,
    created_at timestamp(0) without time zone NOT NULL,
    paid_at timestamp(0) without time zone DEFAULT NULL::timestamp without time zone
);


--
-- Name: fine_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.fine_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: fine_id_seq1; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.fine ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.fine_id_seq1
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: integration_config; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.integration_config (
    id integer NOT NULL,
    name character varying(160) NOT NULL,
    provider character varying(120) NOT NULL,
    enabled boolean NOT NULL,
    settings json NOT NULL,
    last_status character varying(32) NOT NULL,
    last_tested_at timestamp(0) without time zone DEFAULT NULL::timestamp without time zone,
    created_at timestamp(0) without time zone NOT NULL,
    updated_at timestamp(0) without time zone NOT NULL
);


--
-- Name: integration_config_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.integration_config_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: integration_config_id_seq1; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.integration_config ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.integration_config_id_seq1
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: loan; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.loan (
    id integer NOT NULL,
    book_id integer NOT NULL,
    book_copy_id integer,
    user_id integer NOT NULL,
    borrowed_at timestamp(0) without time zone NOT NULL,
    due_at timestamp(0) without time zone NOT NULL,
    returned_at timestamp(0) without time zone DEFAULT NULL::timestamp without time zone,
    extensions_count integer NOT NULL,
    last_extended_at timestamp(0) without time zone DEFAULT NULL::timestamp without time zone
);


--
-- Name: loan_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.loan_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: loan_id_seq1; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.loan ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.loan_id_seq1
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: notification_log; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.notification_log (
    id integer NOT NULL,
    user_id integer NOT NULL,
    type character varying(64) NOT NULL,
    channel character varying(32) NOT NULL,
    fingerprint character varying(96) NOT NULL,
    payload json,
    status character varying(32) NOT NULL,
    error_message character varying(255) DEFAULT NULL::character varying,
    sent_at timestamp(0) without time zone NOT NULL
);


--
-- Name: notification_log_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.notification_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: notification_log_id_seq1; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.notification_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notification_log_id_seq1
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: rating; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.rating (
    id integer NOT NULL,
    rating smallint NOT NULL,
    review text,
    created_at timestamp(0) without time zone NOT NULL,
    updated_at timestamp(0) without time zone DEFAULT NULL::timestamp without time zone,
    user_id integer NOT NULL,
    book_id integer NOT NULL
);


--
-- Name: rating_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.rating ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.rating_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: recommendation_feedback; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.recommendation_feedback (
    id integer NOT NULL,
    feedback_type character varying(20) NOT NULL,
    created_at timestamp(0) without time zone NOT NULL,
    user_id integer NOT NULL,
    book_id integer NOT NULL
);


--
-- Name: recommendation_feedback_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.recommendation_feedback ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.recommendation_feedback_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: refresh_token; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.refresh_token (
    id integer NOT NULL,
    user_id integer NOT NULL,
    token character varying(255) NOT NULL,
    expires_at timestamp(0) without time zone NOT NULL,
    created_at timestamp(0) without time zone NOT NULL,
    ip_address character varying(45) DEFAULT NULL::character varying,
    user_agent character varying(255) DEFAULT NULL::character varying,
    is_revoked boolean NOT NULL,
    revoked_at timestamp(0) without time zone DEFAULT NULL::timestamp without time zone
);


--
-- Name: refresh_token_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.refresh_token_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: refresh_token_id_seq1; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.refresh_token ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.refresh_token_id_seq1
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: registration_token; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.registration_token (
    id integer NOT NULL,
    user_id integer NOT NULL,
    token character varying(96) NOT NULL,
    created_at timestamp(0) without time zone NOT NULL,
    expires_at timestamp(0) without time zone NOT NULL,
    used_at timestamp(0) without time zone DEFAULT NULL::timestamp without time zone
);


--
-- Name: registration_token_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.registration_token_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: registration_token_id_seq1; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.registration_token ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.registration_token_id_seq1
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: reservation; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.reservation (
    id integer NOT NULL,
    book_id integer NOT NULL,
    book_copy_id integer,
    user_id integer NOT NULL,
    status character varying(20) NOT NULL,
    reserved_at timestamp(0) without time zone NOT NULL,
    expires_at timestamp(0) without time zone NOT NULL,
    fulfilled_at timestamp(0) without time zone DEFAULT NULL::timestamp without time zone,
    cancelled_at timestamp(0) without time zone DEFAULT NULL::timestamp without time zone
);


--
-- Name: reservation_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.reservation_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: reservation_id_seq1; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.reservation ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.reservation_id_seq1
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: review; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.review (
    id integer NOT NULL,
    book_id integer NOT NULL,
    user_id integer NOT NULL,
    rating smallint NOT NULL,
    comment text,
    created_at timestamp(0) without time zone NOT NULL,
    updated_at timestamp(0) without time zone NOT NULL
);


--
-- Name: review_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.review_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: review_id_seq1; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.review ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.review_id_seq1
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: staff_role; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.staff_role (
    id integer NOT NULL,
    name character varying(120) NOT NULL,
    role_key character varying(120) NOT NULL,
    modules json NOT NULL,
    description character varying(255) DEFAULT NULL::character varying,
    created_at timestamp(0) without time zone NOT NULL,
    updated_at timestamp(0) without time zone NOT NULL
);


--
-- Name: staff_role_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.staff_role_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: staff_role_id_seq1; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.staff_role ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.staff_role_id_seq1
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: supplier; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.supplier (
    id integer NOT NULL,
    name character varying(180) NOT NULL,
    contact_email character varying(180) DEFAULT NULL::character varying,
    contact_phone character varying(60) DEFAULT NULL::character varying,
    address_line character varying(255) DEFAULT NULL::character varying,
    city character varying(120) DEFAULT NULL::character varying,
    country character varying(120) DEFAULT NULL::character varying,
    tax_identifier character varying(60) DEFAULT NULL::character varying,
    notes text,
    active boolean DEFAULT true NOT NULL,
    created_at timestamp(0) without time zone NOT NULL,
    updated_at timestamp(0) without time zone NOT NULL
);


--
-- Name: supplier_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.supplier_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: supplier_id_seq1; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.supplier ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.supplier_id_seq1
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: system_setting; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.system_setting (
    id integer NOT NULL,
    setting_key character varying(120) NOT NULL,
    setting_value text NOT NULL,
    value_type character varying(16) NOT NULL,
    description character varying(255) DEFAULT NULL::character varying,
    created_at timestamp(0) without time zone NOT NULL,
    updated_at timestamp(0) without time zone NOT NULL
);


--
-- Name: system_setting_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.system_setting_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: system_setting_id_seq1; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.system_setting ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.system_setting_id_seq1
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: weeding_record; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.weeding_record (
    id integer NOT NULL,
    book_id integer NOT NULL,
    book_copy_id integer,
    processed_by_id integer,
    reason character varying(255) NOT NULL,
    action character varying(20) NOT NULL,
    condition_state character varying(120) DEFAULT NULL::character varying,
    notes text,
    removed_at timestamp(0) without time zone NOT NULL
);


--
-- Name: weeding_record_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.weeding_record_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: weeding_record_id_seq1; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.weeding_record ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.weeding_record_id_seq1
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: acquisition_budget acquisition_budget_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.acquisition_budget
    ADD CONSTRAINT acquisition_budget_pkey PRIMARY KEY (id);


--
-- Name: acquisition_expense acquisition_expense_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.acquisition_expense
    ADD CONSTRAINT acquisition_expense_pkey PRIMARY KEY (id);


--
-- Name: acquisition_order acquisition_order_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.acquisition_order
    ADD CONSTRAINT acquisition_order_pkey PRIMARY KEY (id);


--
-- Name: announcement announcement_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.announcement
    ADD CONSTRAINT announcement_pkey PRIMARY KEY (id);


--
-- Name: app_user app_user_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_user
    ADD CONSTRAINT app_user_pkey PRIMARY KEY (id);


--
-- Name: audit_logs audit_logs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.audit_logs
    ADD CONSTRAINT audit_logs_pkey PRIMARY KEY (id);


--
-- Name: author author_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.author
    ADD CONSTRAINT author_pkey PRIMARY KEY (id);


--
-- Name: backup_record backup_record_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.backup_record
    ADD CONSTRAINT backup_record_pkey PRIMARY KEY (id);


--
-- Name: book_category book_category_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.book_category
    ADD CONSTRAINT book_category_pkey PRIMARY KEY (book_id, category_id);


--
-- Name: book_collection book_collection_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.book_collection
    ADD CONSTRAINT book_collection_pkey PRIMARY KEY (id);


--
-- Name: book_copy book_copy_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.book_copy
    ADD CONSTRAINT book_copy_pkey PRIMARY KEY (id);


--
-- Name: book_digital_asset book_digital_asset_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.book_digital_asset
    ADD CONSTRAINT book_digital_asset_pkey PRIMARY KEY (id);


--
-- Name: book book_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.book
    ADD CONSTRAINT book_pkey PRIMARY KEY (id);


--
-- Name: category category_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.category
    ADD CONSTRAINT category_pkey PRIMARY KEY (id);


--
-- Name: collection_books collection_books_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.collection_books
    ADD CONSTRAINT collection_books_pkey PRIMARY KEY (book_collection_id, book_id);


--
-- Name: doctrine_migration_versions doctrine_migration_versions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.doctrine_migration_versions
    ADD CONSTRAINT doctrine_migration_versions_pkey PRIMARY KEY (version);


--
-- Name: favorite favorite_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.favorite
    ADD CONSTRAINT favorite_pkey PRIMARY KEY (id);


--
-- Name: user_book_interaction user_book_interaction_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_book_interaction
    ADD CONSTRAINT user_book_interaction_pkey PRIMARY KEY (id);


--
-- Name: fine fine_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.fine
    ADD CONSTRAINT fine_pkey PRIMARY KEY (id);


--
-- Name: integration_config integration_config_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.integration_config
    ADD CONSTRAINT integration_config_pkey PRIMARY KEY (id);


--
-- Name: loan loan_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.loan
    ADD CONSTRAINT loan_pkey PRIMARY KEY (id);


--
-- Name: notification_log notification_log_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notification_log
    ADD CONSTRAINT notification_log_pkey PRIMARY KEY (id);


--
-- Name: rating rating_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.rating
    ADD CONSTRAINT rating_pkey PRIMARY KEY (id);


--
-- Name: recommendation_feedback recommendation_feedback_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recommendation_feedback
    ADD CONSTRAINT recommendation_feedback_pkey PRIMARY KEY (id);


--
-- Name: refresh_token refresh_token_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.refresh_token
    ADD CONSTRAINT refresh_token_pkey PRIMARY KEY (id);


--
-- Name: registration_token registration_token_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.registration_token
    ADD CONSTRAINT registration_token_pkey PRIMARY KEY (id);


--
-- Name: reservation reservation_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reservation
    ADD CONSTRAINT reservation_pkey PRIMARY KEY (id);


--
-- Name: review review_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.review
    ADD CONSTRAINT review_pkey PRIMARY KEY (id);


--
-- Name: staff_role staff_role_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.staff_role
    ADD CONSTRAINT staff_role_pkey PRIMARY KEY (id);


--
-- Name: supplier supplier_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.supplier
    ADD CONSTRAINT supplier_pkey PRIMARY KEY (id);


--
-- Name: system_setting system_setting_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.system_setting
    ADD CONSTRAINT system_setting_pkey PRIMARY KEY (id);


--
-- Name: weeding_record weeding_record_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.weeding_record
    ADD CONSTRAINT weeding_record_pkey PRIMARY KEY (id);


--
-- Name: favorite_user_book_unique; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX favorite_user_book_unique ON public.favorite USING btree (user_id, book_id);


--
-- Name: idx_1e96eaf32add6d8c; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_1e96eaf32add6d8c ON public.acquisition_order USING btree (supplier_id);


--
-- Name: idx_1e96eaf336aba6b8; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_1e96eaf336aba6b8 ON public.acquisition_order USING btree (budget_id);


--
-- Name: idx_1fb30f9812469de2; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_1fb30f9812469de2 ON public.book_category USING btree (category_id);


--
-- Name: idx_1fb30f9816a2b381; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_1fb30f9816a2b381 ON public.book_category USING btree (book_id);


--
-- Name: idx_42c8495516a2b381; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_42c8495516a2b381 ON public.reservation USING btree (book_id);


--
-- Name: idx_42c849553b550fe4; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_42c849553b550fe4 ON public.reservation USING btree (book_copy_id);


--
-- Name: idx_42c84955a76ed395; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_42c84955a76ed395 ON public.reservation USING btree (user_id);


--
-- Name: idx_4db9d91cb03a8386; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_4db9d91cb03a8386 ON public.announcement USING btree (created_by_id);


--
-- Name: idx_5427f08a16a2b381; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_5427f08a16a2b381 ON public.book_copy USING btree (book_id);


--
-- Name: idx_63e02f81436fbb41; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_63e02f81436fbb41 ON public.book_collection USING btree (curated_by_id);


--
-- Name: idx_68c58ed916a2b381; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_68c58ed916a2b381 ON public.favorite USING btree (book_id);


--
-- Name: idx_68c58ed9a76ed395; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_68c58ed9a76ed395 ON public.favorite USING btree (user_id);


--
-- Name: idx_794381c616a2b381; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_794381c616a2b381 ON public.review USING btree (book_id);


--
-- Name: idx_794381c6a76ed395; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_794381c6a76ed395 ON public.review USING btree (user_id);


--
-- Name: idx_812f8cef16a2b381; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_812f8cef16a2b381 ON public.weeding_record USING btree (book_id);


--
-- Name: idx_812f8cef2ffd4fd3; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_812f8cef2ffd4fd3 ON public.weeding_record USING btree (processed_by_id);


--
-- Name: idx_812f8cef3b550fe4; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_812f8cef3b550fe4 ON public.weeding_record USING btree (book_copy_id);


--
-- Name: idx_817c37d016a2b381; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_817c37d016a2b381 ON public.book_digital_asset USING btree (book_id);


--
-- Name: idx_82ea1ded36aba6b8; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_82ea1ded36aba6b8 ON public.acquisition_expense USING btree (budget_id);


--
-- Name: idx_82ea1ded8d9f6d38; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_82ea1ded8d9f6d38 ON public.acquisition_expense USING btree (order_id);


--
-- Name: idx_audit_action; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_audit_action ON public.audit_logs USING btree (action);


--
-- Name: idx_audit_created; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_audit_created ON public.audit_logs USING btree (created_at);


--
-- Name: idx_audit_entity; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_audit_entity ON public.audit_logs USING btree (entity_type, entity_id);


--
-- Name: idx_audit_user; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_audit_user ON public.audit_logs USING btree (user_id);


--
-- Name: idx_bea95492ce73868f; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_bea95492ce73868f ON public.fine USING btree (loan_id);


--
-- Name: idx_c5d30d0316a2b381; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_c5d30d0316a2b381 ON public.loan USING btree (book_id);


--
-- Name: idx_c5d30d033b550fe4; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_c5d30d033b550fe4 ON public.loan USING btree (book_copy_id);


--
-- Name: idx_c5d30d03a76ed395; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_c5d30d03a76ed395 ON public.loan USING btree (user_id);


--
-- Name: idx_cbe5a331f675f31b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_cbe5a331f675f31b ON public.book USING btree (author_id);

--
-- Name: book_search_vector_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX book_search_vector_idx ON public.book USING gin (search_vector);


--
-- Name: idx_d09d01d3a76ed395; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_d09d01d3a76ed395 ON public.registration_token USING btree (user_id);


--
-- Name: idx_d14c89216a2b381; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_d14c89216a2b381 ON public.recommendation_feedback USING btree (book_id);


--
-- Name: idx_d14c892a76ed395; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_d14c892a76ed395 ON public.recommendation_feedback USING btree (user_id);


--
-- Name: idx_d889262216a2b381; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_d889262216a2b381 ON public.rating USING btree (book_id);


--
-- Name: idx_d8892622a76ed395; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_d8892622a76ed395 ON public.rating USING btree (user_id);


--
-- Name: idx_de392c116a2b381; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_de392c116a2b381 ON public.collection_books USING btree (book_id);


--
-- Name: idx_de392c134a06ef1; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_de392c134a06ef1 ON public.collection_books USING btree (book_collection_id);


--
-- Name: idx_ed15df2a76ed395; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_ed15df2a76ed395 ON public.notification_log USING btree (user_id);


--
-- Name: idx_refresh_token; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_refresh_token ON public.refresh_token USING btree (token);


--
-- Name: idx_refresh_token_user; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_refresh_token_user ON public.refresh_token USING btree (user_id);


--
-- Name: user_book_interaction_user_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX user_book_interaction_user_idx ON public.user_book_interaction USING btree (user_id);


--
-- Name: registration_token_lookup; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX registration_token_lookup ON public.registration_token USING btree (token);


--
-- Name: review_user_book_unique; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX review_user_book_unique ON public.review USING btree (user_id, book_id);


--
-- Name: uniq_5427f08a3db3ffb6; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uniq_5427f08a3db3ffb6 ON public.book_copy USING btree (inventory_code);


--
-- Name: uniq_64c19c15e237e06; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uniq_64c19c15e237e06 ON public.category USING btree (name);


--
-- Name: uniq_7307c40b5fa1e697; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uniq_7307c40b5fa1e697 ON public.system_setting USING btree (setting_key);


--
-- Name: uniq_817c37d0570eb513; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uniq_817c37d0570eb513 ON public.book_digital_asset USING btree (storage_name);


--
-- Name: uniq_88bdf3e9e7927c74; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uniq_88bdf3e9e7927c74 ON public.app_user USING btree (email);


--
-- Name: uniq_b55ffce53ef22fdb; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uniq_b55ffce53ef22fdb ON public.staff_role USING btree (role_key);


--
-- Name: uniq_b55ffce55e237e06; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uniq_b55ffce55e237e06 ON public.staff_role USING btree (name);


--
-- Name: uniq_bdafd8c85e237e06; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uniq_bdafd8c85e237e06 ON public.author USING btree (name);


--
-- Name: uniq_c74f21955f37a13b; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uniq_c74f21955f37a13b ON public.refresh_token USING btree (token);


--
-- Name: uniq_d09d01d35f37a13b; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uniq_d09d01d35f37a13b ON public.registration_token USING btree (token);


--
-- Name: uq_notification_fingerprint_channel; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uq_notification_fingerprint_channel ON public.notification_log USING btree (fingerprint, channel);


--
-- Name: user_book_feedback_unique; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX user_book_feedback_unique ON public.recommendation_feedback USING btree (user_id, book_id);


--
-- Name: user_book_unique; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX user_book_unique ON public.rating USING btree (user_id, book_id);


--
-- Name: acquisition_order fk_1e96eaf32add6d8c; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.acquisition_order
    ADD CONSTRAINT fk_1e96eaf32add6d8c FOREIGN KEY (supplier_id) REFERENCES public.supplier(id) ON DELETE RESTRICT;


--
-- Name: acquisition_order fk_1e96eaf336aba6b8; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.acquisition_order
    ADD CONSTRAINT fk_1e96eaf336aba6b8 FOREIGN KEY (budget_id) REFERENCES public.acquisition_budget(id) ON DELETE SET NULL;


--
-- Name: book_category fk_1fb30f9812469de2; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.book_category
    ADD CONSTRAINT fk_1fb30f9812469de2 FOREIGN KEY (category_id) REFERENCES public.category(id) ON DELETE CASCADE;


--
-- Name: book_category fk_1fb30f9816a2b381; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.book_category
    ADD CONSTRAINT fk_1fb30f9816a2b381 FOREIGN KEY (book_id) REFERENCES public.book(id) ON DELETE CASCADE;


--
-- Name: reservation fk_42c8495516a2b381; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reservation
    ADD CONSTRAINT fk_42c8495516a2b381 FOREIGN KEY (book_id) REFERENCES public.book(id) ON DELETE CASCADE;


--
-- Name: reservation fk_42c849553b550fe4; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reservation
    ADD CONSTRAINT fk_42c849553b550fe4 FOREIGN KEY (book_copy_id) REFERENCES public.book_copy(id) ON DELETE SET NULL;


--
-- Name: reservation fk_42c84955a76ed395; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reservation
    ADD CONSTRAINT fk_42c84955a76ed395 FOREIGN KEY (user_id) REFERENCES public.app_user(id) ON DELETE CASCADE;


--
-- Name: announcement fk_4db9d91cb03a8386; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.announcement
    ADD CONSTRAINT fk_4db9d91cb03a8386 FOREIGN KEY (created_by_id) REFERENCES public.app_user(id);


--
-- Name: book_copy fk_5427f08a16a2b381; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.book_copy
    ADD CONSTRAINT fk_5427f08a16a2b381 FOREIGN KEY (book_id) REFERENCES public.book(id) ON DELETE CASCADE;


--
-- Name: book_collection fk_63e02f81436fbb41; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.book_collection
    ADD CONSTRAINT fk_63e02f81436fbb41 FOREIGN KEY (curated_by_id) REFERENCES public.app_user(id) ON DELETE CASCADE;


--
-- Name: favorite fk_68c58ed916a2b381; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.favorite
    ADD CONSTRAINT fk_68c58ed916a2b381 FOREIGN KEY (book_id) REFERENCES public.book(id) ON DELETE CASCADE;


--
-- Name: favorite fk_68c58ed9a76ed395; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.favorite
    ADD CONSTRAINT fk_68c58ed9a76ed395 FOREIGN KEY (user_id) REFERENCES public.app_user(id) ON DELETE CASCADE;


--
-- Name: user_book_interaction fk_user_book_interaction_book; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_book_interaction
    ADD CONSTRAINT fk_user_book_interaction_book FOREIGN KEY (book_id) REFERENCES public.book(id) ON DELETE CASCADE;


--
-- Name: user_book_interaction fk_user_book_interaction_user; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_book_interaction
    ADD CONSTRAINT fk_user_book_interaction_user FOREIGN KEY (user_id) REFERENCES public.app_user(id) ON DELETE CASCADE;


--
-- Name: review fk_794381c616a2b381; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.review
    ADD CONSTRAINT fk_794381c616a2b381 FOREIGN KEY (book_id) REFERENCES public.book(id) ON DELETE CASCADE;


--
-- Name: review fk_794381c6a76ed395; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.review
    ADD CONSTRAINT fk_794381c6a76ed395 FOREIGN KEY (user_id) REFERENCES public.app_user(id) ON DELETE CASCADE;


--
-- Name: weeding_record fk_812f8cef16a2b381; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.weeding_record
    ADD CONSTRAINT fk_812f8cef16a2b381 FOREIGN KEY (book_id) REFERENCES public.book(id) ON DELETE CASCADE;


--
-- Name: weeding_record fk_812f8cef2ffd4fd3; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.weeding_record
    ADD CONSTRAINT fk_812f8cef2ffd4fd3 FOREIGN KEY (processed_by_id) REFERENCES public.app_user(id) ON DELETE SET NULL;


--
-- Name: weeding_record fk_812f8cef3b550fe4; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.weeding_record
    ADD CONSTRAINT fk_812f8cef3b550fe4 FOREIGN KEY (book_copy_id) REFERENCES public.book_copy(id) ON DELETE SET NULL;


--
-- Name: book_digital_asset fk_817c37d016a2b381; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.book_digital_asset
    ADD CONSTRAINT fk_817c37d016a2b381 FOREIGN KEY (book_id) REFERENCES public.book(id) ON DELETE CASCADE;


--
-- Name: acquisition_expense fk_82ea1ded36aba6b8; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.acquisition_expense
    ADD CONSTRAINT fk_82ea1ded36aba6b8 FOREIGN KEY (budget_id) REFERENCES public.acquisition_budget(id) ON DELETE CASCADE;


--
-- Name: acquisition_expense fk_82ea1ded8d9f6d38; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.acquisition_expense
    ADD CONSTRAINT fk_82ea1ded8d9f6d38 FOREIGN KEY (order_id) REFERENCES public.acquisition_order(id) ON DELETE SET NULL;


--
-- Name: fine fk_bea95492ce73868f; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.fine
    ADD CONSTRAINT fk_bea95492ce73868f FOREIGN KEY (loan_id) REFERENCES public.loan(id) ON DELETE CASCADE;


--
-- Name: loan fk_c5d30d0316a2b381; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.loan
    ADD CONSTRAINT fk_c5d30d0316a2b381 FOREIGN KEY (book_id) REFERENCES public.book(id) ON DELETE CASCADE;


--
-- Name: loan fk_c5d30d033b550fe4; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.loan
    ADD CONSTRAINT fk_c5d30d033b550fe4 FOREIGN KEY (book_copy_id) REFERENCES public.book_copy(id) ON DELETE SET NULL;


--
-- Name: loan fk_c5d30d03a76ed395; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.loan
    ADD CONSTRAINT fk_c5d30d03a76ed395 FOREIGN KEY (user_id) REFERENCES public.app_user(id) ON DELETE CASCADE;


--
-- Name: refresh_token fk_c74f2195a76ed395; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.refresh_token
    ADD CONSTRAINT fk_c74f2195a76ed395 FOREIGN KEY (user_id) REFERENCES public.app_user(id) ON DELETE CASCADE;


--
-- Name: book fk_cbe5a331f675f31b; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.book
    ADD CONSTRAINT fk_cbe5a331f675f31b FOREIGN KEY (author_id) REFERENCES public.author(id) ON DELETE RESTRICT;


--
-- Name: registration_token fk_d09d01d3a76ed395; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.registration_token
    ADD CONSTRAINT fk_d09d01d3a76ed395 FOREIGN KEY (user_id) REFERENCES public.app_user(id) ON DELETE CASCADE;


--
-- Name: recommendation_feedback fk_d14c89216a2b381; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recommendation_feedback
    ADD CONSTRAINT fk_d14c89216a2b381 FOREIGN KEY (book_id) REFERENCES public.book(id) ON DELETE CASCADE;


--
-- Name: recommendation_feedback fk_d14c892a76ed395; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recommendation_feedback
    ADD CONSTRAINT fk_d14c892a76ed395 FOREIGN KEY (user_id) REFERENCES public.app_user(id) ON DELETE CASCADE;


--
-- Name: audit_logs fk_d62f2858a76ed395; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.audit_logs
    ADD CONSTRAINT fk_d62f2858a76ed395 FOREIGN KEY (user_id) REFERENCES public.app_user(id) ON DELETE SET NULL;


--
-- Name: rating fk_d889262216a2b381; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.rating
    ADD CONSTRAINT fk_d889262216a2b381 FOREIGN KEY (book_id) REFERENCES public.book(id) ON DELETE CASCADE;


--
-- Name: rating fk_d8892622a76ed395; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.rating
    ADD CONSTRAINT fk_d8892622a76ed395 FOREIGN KEY (user_id) REFERENCES public.app_user(id) ON DELETE CASCADE;


--
-- Name: collection_books fk_de392c116a2b381; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.collection_books
    ADD CONSTRAINT fk_de392c116a2b381 FOREIGN KEY (book_id) REFERENCES public.book(id) ON DELETE CASCADE;


--
-- Name: collection_books fk_de392c134a06ef1; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.collection_books
    ADD CONSTRAINT fk_de392c134a06ef1 FOREIGN KEY (book_collection_id) REFERENCES public.book_collection(id) ON DELETE CASCADE;


--
-- Name: notification_log fk_ed15df2a76ed395; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notification_log
    ADD CONSTRAINT fk_ed15df2a76ed395 FOREIGN KEY (user_id) REFERENCES public.app_user(id) ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

\unrestrict KRk9mMtl7CqE4DbKcqoEWRarLYpKaMxndigQjQ46HzXsFmvcR80srafX9XnI1RO

