<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXTdcmsS\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXTdcmsS/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXTdcmsS.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXTdcmsS\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXTdcmsS\App_KernelDevDebugContainer([
    'container.build_hash' => 'XTdcmsS',
    'container.build_id' => '8bb2e9e7',
    'container.build_time' => 1765444238,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXTdcmsS');
