<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGUJAncJ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGUJAncJ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGUJAncJ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGUJAncJ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerGUJAncJ\App_KernelDevDebugContainer([
    'container.build_hash' => 'GUJAncJ',
    'container.build_id' => 'a367d9f8',
    'container.build_time' => 1765553963,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGUJAncJ');
