<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerObaez85\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerObaez85/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerObaez85.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerObaez85\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerObaez85\App_KernelDevDebugContainer([
    'container.build_hash' => 'Obaez85',
    'container.build_id' => '17500275',
    'container.build_time' => 1763278680,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerObaez85');
