<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251213074339 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE acquisition_budget ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('COMMENT ON COLUMN acquisition_budget.created_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN acquisition_budget.updated_at IS \'\'');
        $this->addSql('ALTER TABLE acquisition_expense ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('COMMENT ON COLUMN acquisition_expense.posted_at IS \'\'');
        $this->addSql('ALTER TABLE acquisition_order ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('COMMENT ON COLUMN acquisition_order.created_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN acquisition_order.updated_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN acquisition_order.ordered_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN acquisition_order.expected_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN acquisition_order.received_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN acquisition_order.cancelled_at IS \'\'');
        $this->addSql('ALTER TABLE announcement ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('COMMENT ON COLUMN announcement.created_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN announcement.updated_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN announcement.published_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN announcement.expires_at IS \'\'');
        $this->addSql('ALTER TABLE app_user ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('COMMENT ON COLUMN app_user.verified_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN app_user.created_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN app_user.updated_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN app_user.privacy_consent_at IS \'\'');
        $this->addSql('ALTER TABLE audit_logs ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('COMMENT ON COLUMN audit_logs.created_at IS \'\'');
        $this->addSql('ALTER TABLE author ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE backup_record ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('COMMENT ON COLUMN backup_record.created_at IS \'\'');
        $this->addSql('ALTER TABLE book ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE book_copy ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('COMMENT ON COLUMN book_copy.created_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN book_copy.updated_at IS \'\'');
        $this->addSql('ALTER TABLE book_digital_asset ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('COMMENT ON COLUMN book_digital_asset.created_at IS \'\'');
        $this->addSql('ALTER TABLE category ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE favorite ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE favorite ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('COMMENT ON COLUMN favorite.created_at IS \'\'');
        $this->addSql('ALTER TABLE fine ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE fine ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('COMMENT ON COLUMN fine.created_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN fine.paid_at IS \'\'');
        $this->addSql('ALTER TABLE integration_config ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('COMMENT ON COLUMN integration_config.last_tested_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN integration_config.created_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN integration_config.updated_at IS \'\'');
        $this->addSql('ALTER TABLE loan ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE loan ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE notification_log ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('COMMENT ON COLUMN notification_log.sent_at IS \'\'');
        $this->addSql('ALTER TABLE refresh_token ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE refresh_token ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('COMMENT ON COLUMN refresh_token.expires_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN refresh_token.created_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN refresh_token.revoked_at IS \'\'');
        $this->addSql('ALTER TABLE registration_token ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('COMMENT ON COLUMN registration_token.created_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN registration_token.expires_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN registration_token.used_at IS \'\'');
        $this->addSql('ALTER TABLE reservation ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE reservation ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('COMMENT ON COLUMN reservation.reserved_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN reservation.expires_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN reservation.fulfilled_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN reservation.cancelled_at IS \'\'');
        $this->addSql('ALTER TABLE review ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('COMMENT ON COLUMN review.created_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN review.updated_at IS \'\'');
        $this->addSql('ALTER TABLE staff_role ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('COMMENT ON COLUMN staff_role.created_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN staff_role.updated_at IS \'\'');
        $this->addSql('ALTER TABLE supplier ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('COMMENT ON COLUMN supplier.created_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN supplier.updated_at IS \'\'');
        $this->addSql('ALTER TABLE system_setting ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('COMMENT ON COLUMN system_setting.created_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN system_setting.updated_at IS \'\'');
        $this->addSql('ALTER TABLE weeding_record ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('COMMENT ON COLUMN weeding_record.removed_at IS \'\'');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE acquisition_budget ALTER id DROP IDENTITY');
        $this->addSql('COMMENT ON COLUMN acquisition_budget.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN acquisition_budget.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE acquisition_expense ALTER id DROP IDENTITY');
        $this->addSql('COMMENT ON COLUMN acquisition_expense.posted_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE acquisition_order ALTER id DROP IDENTITY');
        $this->addSql('COMMENT ON COLUMN acquisition_order.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN acquisition_order.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN acquisition_order.ordered_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN acquisition_order.expected_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN acquisition_order.received_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN acquisition_order.cancelled_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE announcement ALTER id DROP IDENTITY');
        $this->addSql('COMMENT ON COLUMN announcement.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN announcement.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN announcement.published_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN announcement.expires_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE app_user ALTER id DROP IDENTITY');
        $this->addSql('COMMENT ON COLUMN app_user.verified_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN app_user.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN app_user.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN app_user.privacy_consent_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE audit_logs ALTER id DROP IDENTITY');
        $this->addSql('COMMENT ON COLUMN audit_logs.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE author ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE backup_record ALTER id DROP IDENTITY');
        $this->addSql('COMMENT ON COLUMN backup_record.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE book ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE book_copy ALTER id DROP IDENTITY');
        $this->addSql('COMMENT ON COLUMN book_copy.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN book_copy.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE book_digital_asset ALTER id DROP IDENTITY');
        $this->addSql('COMMENT ON COLUMN book_digital_asset.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE category ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE favorite ALTER id SET DEFAULT nextval(\'favorite_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE favorite ALTER id DROP IDENTITY');
        $this->addSql('COMMENT ON COLUMN favorite.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE fine ALTER id SET DEFAULT nextval(\'fine_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE fine ALTER id DROP IDENTITY');
        $this->addSql('COMMENT ON COLUMN fine.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN fine.paid_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE integration_config ALTER id DROP IDENTITY');
        $this->addSql('COMMENT ON COLUMN integration_config.last_tested_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN integration_config.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN integration_config.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE loan ALTER id SET DEFAULT nextval(\'loan_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE loan ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE notification_log ALTER id DROP IDENTITY');
        $this->addSql('COMMENT ON COLUMN notification_log.sent_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE refresh_token ALTER id SET DEFAULT nextval(\'refresh_token_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE refresh_token ALTER id DROP IDENTITY');
        $this->addSql('COMMENT ON COLUMN refresh_token.expires_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN refresh_token.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN refresh_token.revoked_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE registration_token ALTER id DROP IDENTITY');
        $this->addSql('COMMENT ON COLUMN registration_token.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN registration_token.expires_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN registration_token.used_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE reservation ALTER id SET DEFAULT nextval(\'reservation_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE reservation ALTER id DROP IDENTITY');
        $this->addSql('COMMENT ON COLUMN reservation.reserved_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN reservation.expires_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN reservation.fulfilled_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN reservation.cancelled_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE review ALTER id DROP IDENTITY');
        $this->addSql('COMMENT ON COLUMN review.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN review.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE staff_role ALTER id DROP IDENTITY');
        $this->addSql('COMMENT ON COLUMN staff_role.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN staff_role.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE supplier ALTER id DROP IDENTITY');
        $this->addSql('COMMENT ON COLUMN supplier.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN supplier.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE system_setting ALTER id DROP IDENTITY');
        $this->addSql('COMMENT ON COLUMN system_setting.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN system_setting.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE weeding_record ALTER id DROP IDENTITY');
        $this->addSql('COMMENT ON COLUMN weeding_record.removed_at IS \'(DC2Type:datetime_immutable)\'');
    }
}
