<?php
declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260107210000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Align supplier/weeding/staff_role schema with current entities';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE IF NOT EXISTS staff_role (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            name VARCHAR(120) NOT NULL,
            role_key VARCHAR(120) NOT NULL,
            modules JSON NOT NULL,
            description VARCHAR(255) DEFAULT NULL,
            created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            PRIMARY KEY(id)
        )');
        $this->addSql('CREATE UNIQUE INDEX IF NOT EXISTS UNIQ_B55FFCE55E237E06 ON staff_role (name)');
        $this->addSql('CREATE UNIQUE INDEX IF NOT EXISTS UNIQ_B55FFCE53EF22FDB ON staff_role (role_key)');

        $this->addSql('ALTER TABLE supplier ADD COLUMN IF NOT EXISTS contact_email VARCHAR(180) DEFAULT NULL');
        $this->addSql('ALTER TABLE supplier ADD COLUMN IF NOT EXISTS contact_phone VARCHAR(60) DEFAULT NULL');
        $this->addSql('ALTER TABLE supplier ADD COLUMN IF NOT EXISTS address_line VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE supplier ADD COLUMN IF NOT EXISTS city VARCHAR(120) DEFAULT NULL');
        $this->addSql('ALTER TABLE supplier ADD COLUMN IF NOT EXISTS country VARCHAR(120) DEFAULT NULL');
        $this->addSql('ALTER TABLE supplier ADD COLUMN IF NOT EXISTS tax_identifier VARCHAR(60) DEFAULT NULL');
        $this->addSql('ALTER TABLE supplier ADD COLUMN IF NOT EXISTS notes TEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE supplier ADD COLUMN IF NOT EXISTS active BOOLEAN DEFAULT true');
        $this->addSql('UPDATE supplier SET active = true WHERE active IS NULL');
        $this->addSql('ALTER TABLE supplier ALTER COLUMN active SET NOT NULL');

        $this->addSql("DO $$ BEGIN
            IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'supplier' AND column_name = 'email') THEN
                UPDATE supplier SET contact_email = COALESCE(contact_email, email) WHERE email IS NOT NULL;
            END IF;
            IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'supplier' AND column_name = 'phone') THEN
                UPDATE supplier SET contact_phone = COALESCE(contact_phone, phone) WHERE phone IS NOT NULL;
            END IF;
            IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'supplier' AND column_name = 'address') THEN
                UPDATE supplier SET address_line = COALESCE(address_line, address) WHERE address IS NOT NULL;
            END IF;
        END $$;");

        $this->addSql('ALTER TABLE weeding_record ADD COLUMN IF NOT EXISTS book_id INT');
        $this->addSql('ALTER TABLE weeding_record ADD COLUMN IF NOT EXISTS book_copy_id INT');
        $this->addSql('ALTER TABLE weeding_record ADD COLUMN IF NOT EXISTS processed_by_id INT');
        $this->addSql('ALTER TABLE weeding_record ADD COLUMN IF NOT EXISTS action VARCHAR(20) DEFAULT \'DISCARD\'');
        $this->addSql('ALTER TABLE weeding_record ADD COLUMN IF NOT EXISTS condition_state VARCHAR(120) DEFAULT NULL');
        $this->addSql('ALTER TABLE weeding_record ADD COLUMN IF NOT EXISTS notes TEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE weeding_record ADD COLUMN IF NOT EXISTS removed_at TIMESTAMP(0) WITHOUT TIME ZONE');

        $this->addSql("DO $$ BEGIN
            IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'weeding_record' AND column_name = 'weeded_at') THEN
                UPDATE weeding_record SET removed_at = COALESCE(removed_at, weeded_at) WHERE weeded_at IS NOT NULL;
            END IF;
            IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'weeding_record' AND column_name = 'performed_by_id') THEN
                UPDATE weeding_record SET processed_by_id = COALESCE(processed_by_id, performed_by_id) WHERE performed_by_id IS NOT NULL;
            END IF;
        END $$;");

        $this->addSql('UPDATE weeding_record SET action = \'DISCARD\' WHERE action IS NULL OR action = \'\'');
        $this->addSql('UPDATE weeding_record SET removed_at = NOW() WHERE removed_at IS NULL');
        $this->addSql('UPDATE weeding_record wr SET book_id = bc.book_id FROM book_copy bc WHERE wr.book_id IS NULL AND wr.book_copy_id = bc.id');

        $this->addSql("DO $$ BEGIN
            IF NOT EXISTS (SELECT 1 FROM weeding_record WHERE book_id IS NULL) THEN
                ALTER TABLE weeding_record ALTER COLUMN book_id SET NOT NULL;
            END IF;
        END $$;");

        $this->addSql('CREATE INDEX IF NOT EXISTS IDX_WR_BOOK ON weeding_record (book_id)');
        $this->addSql('CREATE INDEX IF NOT EXISTS IDX_WR_COPY ON weeding_record (book_copy_id)');
        $this->addSql('CREATE INDEX IF NOT EXISTS IDX_WR_PROCESSED_BY ON weeding_record (processed_by_id)');

        $this->addSql("DO $$ BEGIN
            IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_WR_BOOK') THEN
                ALTER TABLE weeding_record ADD CONSTRAINT FK_WR_BOOK FOREIGN KEY (book_id) REFERENCES book (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE;
            END IF;
            IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_WR_COPY') THEN
                ALTER TABLE weeding_record ADD CONSTRAINT FK_WR_COPY FOREIGN KEY (book_copy_id) REFERENCES book_copy (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE;
            END IF;
            IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_WR_PROCESSED_BY') THEN
                ALTER TABLE weeding_record ADD CONSTRAINT FK_WR_PROCESSED_BY FOREIGN KEY (processed_by_id) REFERENCES app_user (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE;
            END IF;
        END $$;");
    }

    public function down(Schema $schema): void
    {
        $this->addSql("DO $$ BEGIN
            IF EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_WR_BOOK') THEN
                ALTER TABLE weeding_record DROP CONSTRAINT FK_WR_BOOK;
            END IF;
            IF EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_WR_COPY') THEN
                ALTER TABLE weeding_record DROP CONSTRAINT FK_WR_COPY;
            END IF;
            IF EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_WR_PROCESSED_BY') THEN
                ALTER TABLE weeding_record DROP CONSTRAINT FK_WR_PROCESSED_BY;
            END IF;
        END $$;");

        $this->addSql('DROP INDEX IF EXISTS IDX_WR_BOOK');
        $this->addSql('DROP INDEX IF EXISTS IDX_WR_COPY');
        $this->addSql('DROP INDEX IF EXISTS IDX_WR_PROCESSED_BY');

        $this->addSql('ALTER TABLE weeding_record DROP COLUMN IF EXISTS book_id');
        $this->addSql('ALTER TABLE weeding_record DROP COLUMN IF EXISTS processed_by_id');
        $this->addSql('ALTER TABLE weeding_record DROP COLUMN IF EXISTS action');
        $this->addSql('ALTER TABLE weeding_record DROP COLUMN IF EXISTS condition_state');
        $this->addSql('ALTER TABLE weeding_record DROP COLUMN IF EXISTS notes');
        $this->addSql('ALTER TABLE weeding_record DROP COLUMN IF EXISTS removed_at');

        $this->addSql('ALTER TABLE supplier DROP COLUMN IF EXISTS contact_email');
        $this->addSql('ALTER TABLE supplier DROP COLUMN IF EXISTS contact_phone');
        $this->addSql('ALTER TABLE supplier DROP COLUMN IF EXISTS address_line');
        $this->addSql('ALTER TABLE supplier DROP COLUMN IF EXISTS city');
        $this->addSql('ALTER TABLE supplier DROP COLUMN IF EXISTS country');
        $this->addSql('ALTER TABLE supplier DROP COLUMN IF EXISTS tax_identifier');
        $this->addSql('ALTER TABLE supplier DROP COLUMN IF EXISTS notes');
        $this->addSql('ALTER TABLE supplier DROP COLUMN IF EXISTS active');

        $this->addSql('DROP INDEX IF EXISTS UNIQ_B55FFCE55E237E06');
        $this->addSql('DROP INDEX IF EXISTS UNIQ_B55FFCE53EF22FDB');
        $this->addSql('DROP TABLE IF EXISTS staff_role');
    }
}
