<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20251116103000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add registration workflow metadata to users and create registration_token table.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql("ALTER TABLE app_user ADD verified BOOLEAN DEFAULT false NOT NULL");
        $this->addSql("ALTER TABLE app_user ADD verified_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL");
        $this->addSql("ALTER TABLE app_user ADD pending_approval BOOLEAN DEFAULT false NOT NULL");
        $this->addSql("ALTER TABLE app_user ADD created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL");
        $this->addSql("ALTER TABLE app_user ADD updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL");
        $this->addSql("ALTER TABLE app_user ADD privacy_consent_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL");

        $this->addSql('CREATE TABLE registration_token (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_id INT NOT NULL, token VARCHAR(96) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, used_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_49BE8D1A5F37A13B ON registration_token (token)');
        $this->addSql('CREATE INDEX registration_token_lookup ON registration_token (token)');
        $this->addSql('ALTER TABLE registration_token ADD CONSTRAINT FK_49BE8D1AA76ED395 FOREIGN KEY (user_id) REFERENCES app_user (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');

        $this->addSql('UPDATE app_user SET verified = true, verified_at = NOW(), created_at = COALESCE(created_at, NOW()), updated_at = NOW()');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE registration_token');

        $this->addSql('ALTER TABLE app_user DROP verified');
        $this->addSql('ALTER TABLE app_user DROP verified_at');
        $this->addSql('ALTER TABLE app_user DROP pending_approval');
        $this->addSql('ALTER TABLE app_user DROP created_at');
        $this->addSql('ALTER TABLE app_user DROP updated_at');
        $this->addSql('ALTER TABLE app_user DROP privacy_consent_at');
    }
}
