// Services - barrel exports
export { acquisitionService } from './acquisitionService'
export { aiService } from './aiService'
export { announcementService } from './announcementService'
export { authService } from './authService'
export { backupService } from './backupService'
export { bookService } from './bookService'
export { catalogService } from './catalogService'
export { digitalAssetService } from './digitalAssetService'
export { healthService } from './healthService'
export { inventoryService } from './inventoryService'
export { loanService } from './loanService'
export { notificationService } from './notificationService'
export { ratingService } from './ratingService'
export { reportService } from './reportService'
export { reservationService } from './reservationService'
export { systemLogService } from './systemLogService'
export { userService } from './userService'
