// Services - barrel exports
export { default as acquisitionService } from './acquisitionService'
export { default as announcementService } from './announcementService'
export { authService } from './authService'
export { default as bookService } from './bookService'
export { default as catalogService } from './catalogService'
export { default as digitalAssetService } from './digitalAssetService'
export { default as loanService } from './loanService'
export { default as notificationService } from './notificationService'
export { default as ratingService } from './ratingService'
export { default as reportService } from './reportService'
export { default as reservationService } from './reservationService'
export { default as systemLogService } from './systemLogService'
export { default as userService } from './userService'
