<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Loan extends \App\Entity\Loan implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'book' => [parent::class, 'book', null, 16],
        "\0".parent::class."\0".'bookCopy' => [parent::class, 'bookCopy', null, 16],
        "\0".parent::class."\0".'borrowedAt' => [parent::class, 'borrowedAt', null, 16],
        "\0".parent::class."\0".'dueAt' => [parent::class, 'dueAt', null, 16],
        "\0".parent::class."\0".'extensionsCount' => [parent::class, 'extensionsCount', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'lastExtendedAt' => [parent::class, 'lastExtendedAt', null, 16],
        "\0".parent::class."\0".'returnedAt' => [parent::class, 'returnedAt', null, 16],
        "\0".parent::class."\0".'user' => [parent::class, 'user', null, 16],
        'book' => [parent::class, 'book', null, 16],
        'bookCopy' => [parent::class, 'bookCopy', null, 16],
        'borrowedAt' => [parent::class, 'borrowedAt', null, 16],
        'dueAt' => [parent::class, 'dueAt', null, 16],
        'extensionsCount' => [parent::class, 'extensionsCount', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'lastExtendedAt' => [parent::class, 'lastExtendedAt', null, 16],
        'returnedAt' => [parent::class, 'returnedAt', null, 16],
        'user' => [parent::class, 'user', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
