<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class AcquisitionBudget extends \App\Entity\AcquisitionBudget implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'allocatedAmount' => [parent::class, 'allocatedAmount', null, 16],
        "\0".parent::class."\0".'createdAt' => [parent::class, 'createdAt', null, 16],
        "\0".parent::class."\0".'currency' => [parent::class, 'currency', null, 16],
        "\0".parent::class."\0".'fiscalYear' => [parent::class, 'fiscalYear', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'name' => [parent::class, 'name', null, 16],
        "\0".parent::class."\0".'spentAmount' => [parent::class, 'spentAmount', null, 16],
        "\0".parent::class."\0".'updatedAt' => [parent::class, 'updatedAt', null, 16],
        'allocatedAmount' => [parent::class, 'allocatedAmount', null, 16],
        'createdAt' => [parent::class, 'createdAt', null, 16],
        'currency' => [parent::class, 'currency', null, 16],
        'fiscalYear' => [parent::class, 'fiscalYear', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'name' => [parent::class, 'name', null, 16],
        'spentAmount' => [parent::class, 'spentAmount', null, 16],
        'updatedAt' => [parent::class, 'updatedAt', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
