<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Book extends \App\Entity\Book implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'author' => [parent::class, 'author', null, 16],
        "\0".parent::class."\0".'categories' => [parent::class, 'categories', null, 16],
        "\0".parent::class."\0".'copies' => [parent::class, 'copies', null, 16],
        "\0".parent::class."\0".'createdAt' => [parent::class, 'createdAt', null, 16],
        "\0".parent::class."\0".'description' => [parent::class, 'description', null, 16],
        "\0".parent::class."\0".'digitalAssets' => [parent::class, 'digitalAssets', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'inventory' => [parent::class, 'inventory', null, 16],
        "\0".parent::class."\0".'isFavorite' => [parent::class, 'isFavorite', null, 16],
        "\0".parent::class."\0".'isbn' => [parent::class, 'isbn', null, 16],
        "\0".parent::class."\0".'openStackCopies' => [parent::class, 'openStackCopies', null, 16],
        "\0".parent::class."\0".'publicationYear' => [parent::class, 'publicationYear', null, 16],
        "\0".parent::class."\0".'publisher' => [parent::class, 'publisher', null, 16],
        "\0".parent::class."\0".'resourceType' => [parent::class, 'resourceType', null, 16],
        "\0".parent::class."\0".'signature' => [parent::class, 'signature', null, 16],
        "\0".parent::class."\0".'storageCopies' => [parent::class, 'storageCopies', null, 16],
        "\0".parent::class."\0".'title' => [parent::class, 'title', null, 16],
        "\0".parent::class."\0".'totalCopies' => [parent::class, 'totalCopies', null, 16],
        'author' => [parent::class, 'author', null, 16],
        'categories' => [parent::class, 'categories', null, 16],
        'copies' => [parent::class, 'copies', null, 16],
        'createdAt' => [parent::class, 'createdAt', null, 16],
        'description' => [parent::class, 'description', null, 16],
        'digitalAssets' => [parent::class, 'digitalAssets', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'inventory' => [parent::class, 'inventory', null, 16],
        'isFavorite' => [parent::class, 'isFavorite', null, 16],
        'isbn' => [parent::class, 'isbn', null, 16],
        'openStackCopies' => [parent::class, 'openStackCopies', null, 16],
        'publicationYear' => [parent::class, 'publicationYear', null, 16],
        'publisher' => [parent::class, 'publisher', null, 16],
        'resourceType' => [parent::class, 'resourceType', null, 16],
        'signature' => [parent::class, 'signature', null, 16],
        'storageCopies' => [parent::class, 'storageCopies', null, 16],
        'title' => [parent::class, 'title', null, 16],
        'totalCopies' => [parent::class, 'totalCopies', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
