<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Supplier extends \App\Entity\Supplier implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'active' => [parent::class, 'active', null, 16],
        "\0".parent::class."\0".'addressLine' => [parent::class, 'addressLine', null, 16],
        "\0".parent::class."\0".'city' => [parent::class, 'city', null, 16],
        "\0".parent::class."\0".'contactEmail' => [parent::class, 'contactEmail', null, 16],
        "\0".parent::class."\0".'contactPhone' => [parent::class, 'contactPhone', null, 16],
        "\0".parent::class."\0".'country' => [parent::class, 'country', null, 16],
        "\0".parent::class."\0".'createdAt' => [parent::class, 'createdAt', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'name' => [parent::class, 'name', null, 16],
        "\0".parent::class."\0".'notes' => [parent::class, 'notes', null, 16],
        "\0".parent::class."\0".'taxIdentifier' => [parent::class, 'taxIdentifier', null, 16],
        "\0".parent::class."\0".'updatedAt' => [parent::class, 'updatedAt', null, 16],
        'active' => [parent::class, 'active', null, 16],
        'addressLine' => [parent::class, 'addressLine', null, 16],
        'city' => [parent::class, 'city', null, 16],
        'contactEmail' => [parent::class, 'contactEmail', null, 16],
        'contactPhone' => [parent::class, 'contactPhone', null, 16],
        'country' => [parent::class, 'country', null, 16],
        'createdAt' => [parent::class, 'createdAt', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'name' => [parent::class, 'name', null, 16],
        'notes' => [parent::class, 'notes', null, 16],
        'taxIdentifier' => [parent::class, 'taxIdentifier', null, 16],
        'updatedAt' => [parent::class, 'updatedAt', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
