<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class User extends \App\Entity\User implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'addressLine' => [parent::class, 'addressLine', null, 16],
        "\0".parent::class."\0".'blocked' => [parent::class, 'blocked', null, 16],
        "\0".parent::class."\0".'blockedReason' => [parent::class, 'blockedReason', null, 16],
        "\0".parent::class."\0".'city' => [parent::class, 'city', null, 16],
        "\0".parent::class."\0".'createdAt' => [parent::class, 'createdAt', null, 16],
        "\0".parent::class."\0".'email' => [parent::class, 'email', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'loanLimit' => [parent::class, 'loanLimit', null, 16],
        "\0".parent::class."\0".'membershipGroup' => [parent::class, 'membershipGroup', null, 16],
        "\0".parent::class."\0".'name' => [parent::class, 'name', null, 16],
        "\0".parent::class."\0".'newsletterSubscribed' => [parent::class, 'newsletterSubscribed', null, 16],
        "\0".parent::class."\0".'password' => [parent::class, 'password', null, 16],
        "\0".parent::class."\0".'pendingApproval' => [parent::class, 'pendingApproval', null, 16],
        "\0".parent::class."\0".'phoneNumber' => [parent::class, 'phoneNumber', null, 16],
        "\0".parent::class."\0".'postalCode' => [parent::class, 'postalCode', null, 16],
        "\0".parent::class."\0".'privacyConsentAt' => [parent::class, 'privacyConsentAt', null, 16],
        "\0".parent::class."\0".'roles' => [parent::class, 'roles', null, 16],
        "\0".parent::class."\0".'updatedAt' => [parent::class, 'updatedAt', null, 16],
        "\0".parent::class."\0".'verified' => [parent::class, 'verified', null, 16],
        "\0".parent::class."\0".'verifiedAt' => [parent::class, 'verifiedAt', null, 16],
        'addressLine' => [parent::class, 'addressLine', null, 16],
        'blocked' => [parent::class, 'blocked', null, 16],
        'blockedReason' => [parent::class, 'blockedReason', null, 16],
        'city' => [parent::class, 'city', null, 16],
        'createdAt' => [parent::class, 'createdAt', null, 16],
        'email' => [parent::class, 'email', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'loanLimit' => [parent::class, 'loanLimit', null, 16],
        'membershipGroup' => [parent::class, 'membershipGroup', null, 16],
        'name' => [parent::class, 'name', null, 16],
        'newsletterSubscribed' => [parent::class, 'newsletterSubscribed', null, 16],
        'password' => [parent::class, 'password', null, 16],
        'pendingApproval' => [parent::class, 'pendingApproval', null, 16],
        'phoneNumber' => [parent::class, 'phoneNumber', null, 16],
        'postalCode' => [parent::class, 'postalCode', null, 16],
        'privacyConsentAt' => [parent::class, 'privacyConsentAt', null, 16],
        'roles' => [parent::class, 'roles', null, 16],
        'updatedAt' => [parent::class, 'updatedAt', null, 16],
        'verified' => [parent::class, 'verified', null, 16],
        'verifiedAt' => [parent::class, 'verifiedAt', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
