<?php

namespace ContainerSg1U3hH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Z8H8Dc3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.z8H8Dc3' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.z8H8Dc3'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'doctrine' => ['services', 'doctrine', 'getDoctrineService', true],
            'security' => ['privates', 'App\\Service\\SecurityService', 'getSecurityServiceService', true],
            'bookService' => ['privates', 'App\\Service\\BookService', 'getBookServiceService', true],
        ], [
            'doctrine' => '?',
            'security' => 'App\\Service\\SecurityService',
            'bookService' => 'App\\Service\\BookService',
        ]);
    }
}
