<?php

namespace ContainerSg1U3hH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBookAssetControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\BookAssetController' shared autowired service.
     *
     * @return \App\Controller\BookAssetController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/BookAssetController.php';

        $container->services['App\\Controller\\BookAssetController'] = $instance = new \App\Controller\BookAssetController(($container->services['kernel'] ?? $container->get('kernel', 1)));

        $instance->setContainer(($container->privates['.service_locator.ZyP9f7K'] ?? $container->load('get_ServiceLocator_ZyP9f7KService'))->withContext('App\\Controller\\BookAssetController', $container));

        return $instance;
    }
}
