<?php

namespace ContainerSg1U3hH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOrderLifecycleServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\OrderLifecycleService' shared autowired service.
     *
     * @return \App\Service\OrderLifecycleService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/OrderLifecycleService.php';

        return $container->privates['App\\Service\\OrderLifecycleService'] = new \App\Service\OrderLifecycleService(($container->services['doctrine'] ?? $container->load('getDoctrineService')));
    }
}
