<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class BookCopy extends \App\Entity\BookCopy implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'book' => [parent::class, 'book', null, 16],
        "\0".parent::class."\0".'conditionState' => [parent::class, 'conditionState', null, 16],
        "\0".parent::class."\0".'createdAt' => [parent::class, 'createdAt', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'inventoryCode' => [parent::class, 'inventoryCode', null, 16],
        "\0".parent::class."\0".'location' => [parent::class, 'location', null, 16],
        "\0".parent::class."\0".'status' => [parent::class, 'status', null, 16],
        "\0".parent::class."\0".'updatedAt' => [parent::class, 'updatedAt', null, 16],
        'book' => [parent::class, 'book', null, 16],
        'conditionState' => [parent::class, 'conditionState', null, 16],
        'createdAt' => [parent::class, 'createdAt', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'inventoryCode' => [parent::class, 'inventoryCode', null, 16],
        'location' => [parent::class, 'location', null, 16],
        'status' => [parent::class, 'status', null, 16],
        'updatedAt' => [parent::class, 'updatedAt', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
