<?php

namespace ContainerXYJ847n;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_52eyy9lService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.52eyy9l' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.52eyy9l'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'repo' => ['privates', 'App\\Repository\\BookRepository', 'getBookRepositoryService', true],
            'doctrine' => ['services', 'doctrine', 'getDoctrineService', true],
            'security' => ['privates', 'App\\Service\\SecurityService', 'getSecurityServiceService', true],
            'authorRepository' => ['privates', 'App\\Repository\\AuthorRepository', 'getAuthorRepositoryService', true],
            'categoryRepository' => ['privates', 'App\\Repository\\CategoryRepository', 'getCategoryRepositoryService', true],
        ], [
            'repo' => 'App\\Repository\\BookRepository',
            'doctrine' => '?',
            'security' => 'App\\Service\\SecurityService',
            'authorRepository' => 'App\\Repository\\AuthorRepository',
            'categoryRepository' => 'App\\Repository\\CategoryRepository',
        ]);
    }
}
