<?php

namespace ContainerXYJ847n;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_4aTJiDLService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.4aTJiDL' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.4aTJiDL'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'doctrine' => ['services', 'doctrine', 'getDoctrineService', true],
            'bookService' => ['privates', 'App\\Service\\BookService', 'getBookServiceService', true],
            'security' => ['privates', 'App\\Service\\SecurityService', 'getSecurityServiceService', true],
        ], [
            'doctrine' => '?',
            'bookService' => 'App\\Service\\BookService',
            'security' => 'App\\Service\\SecurityService',
        ]);
    }
}
