<?php

namespace ContainerBss4Vkm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_BRJvpbqService extends App_KernelTestContainer
{
    /*
     * Gets the private '.service_locator.bRJvpbq' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.bRJvpbq'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'doctrine' => ['services', 'doctrine', 'getDoctrineService', true],
            'security' => ['privates', 'App\\Service\\SecurityService', 'getSecurityServiceService', true],
            'orderLifecycle' => ['privates', 'App\\Service\\OrderLifecycleService', 'getOrderLifecycleServiceService', true],
        ], [
            'doctrine' => '?',
            'security' => 'App\\Service\\SecurityService',
            'orderLifecycle' => 'App\\Service\\OrderLifecycleService',
        ]);
    }
}
