<?php

namespace ContainerBss4Vkm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Messenger_HandlerDescriptor_4vlC4aYService extends App_KernelTestContainer
{
    /*
     * Gets the private '.messenger.handler_descriptor.4vlC4aY' shared service.
     *
     * @return \Symfony\Component\Messenger\Handler\HandlerDescriptor
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.messenger.handler_descriptor.4vlC4aY'] = new \Symfony\Component\Messenger\Handler\HandlerDescriptor(($container->privates['App\\MessageHandler\\ReservationQueuedNotificationHandler'] ??= new \App\MessageHandler\ReservationQueuedNotificationHandler(\dirname(__DIR__, 4))), []);
    }
}
