<?php

namespace ContainerBss4Vkm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAcquisitionBudgetRepositoryService extends App_KernelTestContainer
{
    /*
     * Gets the private 'App\Repository\AcquisitionBudgetRepository' shared autowired service.
     *
     * @return \App\Repository\AcquisitionBudgetRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\AcquisitionBudgetRepository'] = new \App\Repository\AcquisitionBudgetRepository(($container->services['doctrine'] ?? $container->load('getDoctrineService')));
    }
}
