<?php

namespace ContainerBss4Vkm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAcquisitionOrderRepositoryService extends App_KernelTestContainer
{
    /*
     * Gets the private 'App\Repository\AcquisitionOrderRepository' shared autowired service.
     *
     * @return \App\Repository\AcquisitionOrderRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\AcquisitionOrderRepository'] = new \App\Repository\AcquisitionOrderRepository(($container->services['doctrine'] ?? $container->load('getDoctrineService')));
    }
}
