<?php

namespace ContainerBss4Vkm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCatalogAdminControllerService extends App_KernelTestContainer
{
    /*
     * Gets the public 'App\Controller\CatalogAdminController' shared autowired service.
     *
     * @return \App\Controller\CatalogAdminController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\CatalogAdminController'] = $instance = new \App\Controller\CatalogAdminController();

        $instance->setContainer(($container->privates['.service_locator.ZyP9f7K'] ?? $container->load('get_ServiceLocator_ZyP9f7KService'))->withContext('App\\Controller\\CatalogAdminController', $container));

        return $instance;
    }
}
