<?php

namespace ContainerBss4Vkm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDoctrine_Orm_ContainerRepositoryFactoryService extends App_KernelTestContainer
{
    /*
     * Gets the private 'doctrine.orm.container_repository_factory' shared service.
     *
     * @return \Doctrine\Bundle\DoctrineBundle\Repository\ContainerRepositoryFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['doctrine.orm.container_repository_factory'] = new \Doctrine\Bundle\DoctrineBundle\Repository\ContainerRepositoryFactory(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Repository\\AcquisitionBudgetRepository' => ['privates', 'App\\Repository\\AcquisitionBudgetRepository', 'getAcquisitionBudgetRepositoryService', true],
            'App\\Repository\\AcquisitionExpenseRepository' => ['privates', 'App\\Repository\\AcquisitionExpenseRepository', 'getAcquisitionExpenseRepositoryService', true],
            'App\\Repository\\AcquisitionOrderRepository' => ['privates', 'App\\Repository\\AcquisitionOrderRepository', 'getAcquisitionOrderRepositoryService', true],
            'App\\Repository\\AuthorRepository' => ['privates', 'App\\Repository\\AuthorRepository', 'getAuthorRepositoryService', true],
            'App\\Repository\\BookCopyRepository' => ['privates', 'App\\Repository\\BookCopyRepository', 'getBookCopyRepositoryService', true],
            'App\\Repository\\BookDigitalAssetRepository' => ['privates', 'App\\Repository\\BookDigitalAssetRepository', 'getBookDigitalAssetRepositoryService', true],
            'App\\Repository\\BookRepository' => ['privates', 'App\\Repository\\BookRepository', 'getBookRepositoryService', true],
            'App\\Repository\\CategoryRepository' => ['privates', 'App\\Repository\\CategoryRepository', 'getCategoryRepositoryService', true],
            'App\\Repository\\FavoriteRepository' => ['privates', 'App\\Repository\\FavoriteRepository', 'getFavoriteRepositoryService', true],
            'App\\Repository\\FineRepository' => ['privates', 'App\\Repository\\FineRepository', 'getFineRepositoryService', true],
            'App\\Repository\\LoanRepository' => ['privates', 'App\\Repository\\LoanRepository', 'getLoanRepositoryService', true],
            'App\\Repository\\OrderRequestRepository' => ['privates', 'App\\Repository\\OrderRequestRepository', 'getOrderRequestRepositoryService', true],
            'App\\Repository\\ReservationRepository' => ['privates', 'App\\Repository\\ReservationRepository', 'getReservationRepositoryService', true],
            'App\\Repository\\ReviewRepository' => ['privates', 'App\\Repository\\ReviewRepository', 'getReviewRepositoryService', true],
            'App\\Repository\\SupplierRepository' => ['privates', 'App\\Repository\\SupplierRepository', 'getSupplierRepositoryService', true],
            'App\\Repository\\UserRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
            'App\\Repository\\WeedingRecordRepository' => ['privates', 'App\\Repository\\WeedingRecordRepository', 'getWeedingRecordRepositoryService', true],
        ], [
            'App\\Repository\\AcquisitionBudgetRepository' => '?',
            'App\\Repository\\AcquisitionExpenseRepository' => '?',
            'App\\Repository\\AcquisitionOrderRepository' => '?',
            'App\\Repository\\AuthorRepository' => '?',
            'App\\Repository\\BookCopyRepository' => '?',
            'App\\Repository\\BookDigitalAssetRepository' => '?',
            'App\\Repository\\BookRepository' => '?',
            'App\\Repository\\CategoryRepository' => '?',
            'App\\Repository\\FavoriteRepository' => '?',
            'App\\Repository\\FineRepository' => '?',
            'App\\Repository\\LoanRepository' => '?',
            'App\\Repository\\OrderRequestRepository' => '?',
            'App\\Repository\\ReservationRepository' => '?',
            'App\\Repository\\ReviewRepository' => '?',
            'App\\Repository\\SupplierRepository' => '?',
            'App\\Repository\\UserRepository' => '?',
            'App\\Repository\\WeedingRecordRepository' => '?',
        ]));
    }
}
