<?php

namespace ContainerBss4Vkm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getExpireOrdersCommand_LazyService extends App_KernelTestContainer
{
    /*
     * Gets the private '.App\Command\ExpireOrdersCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.App\\Command\\ExpireOrdersCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('app:orders:expire', [], 'Marks overdue pickup orders as expired and releases reserved copies', false, #[\Closure(name: 'App\\Command\\ExpireOrdersCommand')] fn (): \App\Command\ExpireOrdersCommand => ($container->privates['App\\Command\\ExpireOrdersCommand'] ?? $container->load('getExpireOrdersCommandService')));
    }
}
