<?php

namespace ContainerBss4Vkm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMessenger_Transport_SymfonySerializerService extends App_KernelTestContainer
{
    /*
     * Gets the private 'messenger.transport.symfony_serializer' shared service.
     *
     * @return \Symfony\Component\Messenger\Transport\Serialization\Serializer
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['messenger.transport.symfony_serializer'] = new \Symfony\Component\Messenger\Transport\Serialization\Serializer(($container->privates['serializer'] ?? self::getSerializerService($container)), 'json', []);
    }
}
