<?php

namespace ContainerBss4Vkm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNelmioApiDoc_ObjectModel_PropertyDescribers_DictionaryService extends App_KernelTestContainer
{
    /*
     * Gets the private 'nelmio_api_doc.object_model.property_describers.dictionary' shared service.
     *
     * @return \Nelmio\ApiDocBundle\PropertyDescriber\DictionaryPropertyDescriber
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['nelmio_api_doc.object_model.property_describers.dictionary'] = new \Nelmio\ApiDocBundle\PropertyDescriber\DictionaryPropertyDescriber();
    }
}
