<?php

namespace ContainerBss4Vkm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReservationQueuedNotificationHandlerService extends App_KernelTestContainer
{
    /*
     * Gets the private 'App\MessageHandler\ReservationQueuedNotificationHandler' shared autowired service.
     *
     * @return \App\MessageHandler\ReservationQueuedNotificationHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\MessageHandler\\ReservationQueuedNotificationHandler'] = new \App\MessageHandler\ReservationQueuedNotificationHandler(\dirname(__DIR__, 4));
    }
}
