<?php

namespace ContainerBss4Vkm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSecurityServiceService extends App_KernelTestContainer
{
    /*
     * Gets the private 'App\Service\SecurityService' shared autowired service.
     *
     * @return \App\Service\SecurityService
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Service\\SecurityService'] = new \App\Service\SecurityService();
    }
}
