<?php

namespace ContainerBss4Vkm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getWeedingRecordRepositoryService extends App_KernelTestContainer
{
    /*
     * Gets the private 'App\Repository\WeedingRecordRepository' shared autowired service.
     *
     * @return \App\Repository\WeedingRecordRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\WeedingRecordRepository'] = new \App\Repository\WeedingRecordRepository(($container->services['doctrine'] ?? $container->load('getDoctrineService')));
    }
}
