<?php

namespace ContainerGoTErQf;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_9B9HXohService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.9B9HXoh' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.9B9HXoh'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'async' => ['privates', 'messenger.transport.async', 'getMessenger_Transport_AsyncService', true],
            'sync' => ['privates', 'messenger.transport.sync', 'getMessenger_Transport_SyncService', true],
            'messenger.transport.async' => ['privates', 'messenger.transport.async', 'getMessenger_Transport_AsyncService', true],
            'messenger.transport.sync' => ['privates', 'messenger.transport.sync', 'getMessenger_Transport_SyncService', true],
        ], [
            'async' => '?',
            'sync' => '?',
            'messenger.transport.async' => '?',
            'messenger.transport.sync' => '?',
        ]);
    }
}
