<?php

namespace ContainerGiDhGgs;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_SC3DzlService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.S_C3Dzl' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.S_C3Dzl'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'security' => ['privates', 'App\\Service\\SecurityService', 'getSecurityServiceService', true],
        ], [
            'security' => 'App\\Service\\SecurityService',
        ]);
    }
}
