<?php

namespace ContainerIkXagxO;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_M1iKpUCService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.m1iKpUC' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.m1iKpUC'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'doctrine' => ['services', 'doctrine', 'getDoctrineService', true],
            'security' => ['privates', 'App\\Service\\SecurityService', 'getSecurityServiceService', true],
            'bus' => ['services', 'messenger.default_bus', 'getMessenger_DefaultBusService', true],
        ], [
            'doctrine' => '?',
            'security' => 'App\\Service\\SecurityService',
            'bus' => '?',
        ]);
    }
}
