<?php

namespace ContainerKSUy3sx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_FQV0aqSService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.fQV0aqS' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.fQV0aqS'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'repo' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
            'doctrine' => ['services', 'doctrine', 'getDoctrineService', true],
            'security' => ['privates', 'App\\Service\\SecurityService', 'getSecurityServiceService', true],
        ], [
            'repo' => 'App\\Repository\\UserRepository',
            'doctrine' => '?',
            'security' => 'App\\Service\\SecurityService',
        ]);
    }
}
