<?php

namespace ContainerRadq6SF;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ClYVSdVService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ClYVSdV' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ClYVSdV'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'bookRepository' => ['privates', 'App\\Repository\\BookRepository', 'getBookRepositoryService', true],
            'assetRepository' => ['privates', 'App\\Repository\\BookDigitalAssetRepository', 'getBookDigitalAssetRepositoryService', true],
            'security' => ['privates', 'App\\Service\\SecurityService', 'getSecurityServiceService', true],
        ], [
            'bookRepository' => 'App\\Repository\\BookRepository',
            'assetRepository' => 'App\\Repository\\BookDigitalAssetRepository',
            'security' => 'App\\Service\\SecurityService',
        ]);
    }
}
