<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXuEcokq\App_KernelTestContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXuEcokq/App_KernelTestContainer.php') {
    touch(__DIR__.'/ContainerXuEcokq.legacy');

    return;
}

if (!\class_exists(App_KernelTestContainer::class, false)) {
    \class_alias(\ContainerXuEcokq\App_KernelTestContainer::class, App_KernelTestContainer::class, false);
}

return new \ContainerXuEcokq\App_KernelTestContainer([
    'container.build_hash' => 'XuEcokq',
    'container.build_id' => 'ec8e2314',
    'container.build_time' => 1763760170,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXuEcokq');
