<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKROCP8e\App_KernelTestContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKROCP8e/App_KernelTestContainer.php') {
    touch(__DIR__.'/ContainerKROCP8e.legacy');

    return;
}

if (!\class_exists(App_KernelTestContainer::class, false)) {
    \class_alias(\ContainerKROCP8e\App_KernelTestContainer::class, App_KernelTestContainer::class, false);
}

return new \ContainerKROCP8e\App_KernelTestContainer([
    'container.build_hash' => 'KROCP8e',
    'container.build_id' => '6fe9e103',
    'container.build_time' => 1762767546,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKROCP8e');
