<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMhscBMK\App_KernelTestContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMhscBMK/App_KernelTestContainer.php') {
    touch(__DIR__.'/ContainerMhscBMK.legacy');

    return;
}

if (!\class_exists(App_KernelTestContainer::class, false)) {
    \class_alias(\ContainerMhscBMK\App_KernelTestContainer::class, App_KernelTestContainer::class, false);
}

return new \ContainerMhscBMK\App_KernelTestContainer([
    'container.build_hash' => 'MhscBMK',
    'container.build_id' => '12b1844d',
    'container.build_time' => 1763730952,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMhscBMK');
